export default {
  conflictKeys:
    '"{{ conflictLabel }}" is already using the "{{ conflictKey }}" shortcut.',
  'hotkey-modifier':
    "It's not possible to define only modifier keys (ctrl, alt and shift) as a shortcut",
  'hotkey-empty': "Field can't be empty.",
  disallowedKey: '"{{ pressedKeys }}" shortcut combination is not allowed',
  ViewMode: 'View mode',
  WindowLevelTools: 'Window level',
  Rotation: 'Rotation',
  Info: 'Information',
  'CHEST_XRAY.content':
    '<p><strong>VinDr-ChestXR</strong>&nbsp;is a CAD tool for chest X-ray interpretation. It is able to localize 18 types of common abnormalities on chest X-ray.</p><p>The system has been trained and validated on half a million chest X-ray studies from both public sources and several hospitals in Vietnam. The bounding box annotation and disease labeling for our private dataset have been performed by top Vietnamese radiologists. The accuracy of the system is above 90% for almost all diseases and findings.</p>',
  'CHEST_XRAY.input':
    '<ul><li><p>An input to VinDr-ChestXR must be a DICOM X-ray image of the chest at either posterior-anterior (<strong>PA</strong>) or anterior-posterior (<strong>AP</strong>) view</p></li><li><p>Patient age at least 16 years old</p></li><li><p>List of required DICOM tags for the input to VinDr-ChestXR. Required values for each tag are also given:</p><ul><li><p>Modality(0008, 0060): CR or DX or DR</p></li><li><p>PhotometricInterpretation(0028, 0004): Non-empty</p></li><li><p>PresentationIntentType(0008, 00068): FOR PRESENTATION</p></li></ul></li></ul>',
  'CHEST_XRAY.output':
    '<p>The analysis of VinDr-ChestXR includes:</p><ul><li><p>A lesion detection: each lesion on the image is surrounded with a rectangle and labeled with one of the pre-defined lesion classes as indicated in below given list:</p><ul><li><p>Aortic enlargement</p></li><li><p>Atelectasis</p></li><li><p>Calcification</p></li><li><p>Cardiomegaly</p></li><li><p>Clavicle fracture</p></li><li><p>Consolidation</p></li><li><p>Emphysema</p></li><li><p>Enlarged PA</p></li><li><p>Infiltration</p></li><li><p>ILD</p></li><li><p>Nodule/Mass</p></li><li><p>Opacity</p></li><li><p>Pleural effusion</p></li><li><p>Pleural thickening</p></li><li><p>Pneumothorax</p></li><li><p>Pulmonary fibrosis</p></li><li><p>Rib fracture</p></li><li><p>Other lesion</p></li></ul></li><li><p>An image classification: each image is classified in terms of normal/abnormal</p></li></ul>',
  'SPINE_XR.content':
    '<p><strong>VinDr-SpineXR</strong> is a CAD tool for spine x-ray interpretation. It is able to classify a spine X-ray scan as normal and abnormal. The system can also localize <strong>6</strong> types of common abnormalities on the image.</p><p>VinDr-SpineXR has been trained and validated on a large-scale dataset of approximately <strong>10,000</strong> studies collected from several hospitals in Vietnam, in which the bounding box annotation and disease labeling have been performed by top Vietnamese radiologists. The accuracy for the abnormality detection is about <strong>60%</strong> in terms of mAP@0.2.</p>',
  'SPINE_XR.input':
    '<ul><li>An input to VinDr-SpineXR must be a DICOM image that depicts cervical, thoracic or lumbar spine at either posterior-anterior (<strong>PA</strong>) or anterior-posterior (<strong>AP</strong>) view</li><li>Patient age at least 16 years old</li><li>List of required DICOM tags for the input to VinDr-ChestXR. Required values for each tag are also given:<ul><li>Modality(0008, 0060): CR or DX or DR</li><li>PhotometricInterpretation(0028, 0004): Non-empty</li><li>PresentationIntentType(0008, 00068): FOR PRESENTATION</li><li>RescaleIntercept(0028, 1052): Non-empty</li><li>RescaleSlope(0028,1053): Non-empty</li><li>WindowCenter(0028,1050): Non-empty</li><li>WindowWidth(0028,1051): Non-empty</li></ul></li></ul>',
  'SPINE_XR.output':
    'The analysis of VinDr-ChestXR includes:<ul><li>A lesion detection: each lesion on the image is surrounded with a rectangle and labeled with one of the pre-defined lesion classes as indicated in below given list:<ul><li>Disc space narrowing</li><li>Foraminal stenosis</li><li>Osteophytes</li><li>Spondylolysthesis</li><li>Surgical implant</li><li>Vertebral collapse</li></ul></li><li>An image classification: each image is classified in terms of normal/abnormal</li></ul>Noting that there may be cases where the image classification is abnormal but no lesion is given since the lesion appeared in the image may not belong to any of the 6 types aforementioned.',
  'MAMMOGRAPHY.content':
    '<p><strong>VinDr-Mammo</strong>&nbsp;is a CAD tool&nbsp;for mammography interpretation. It is able to classify a mammography study into 3 BI-RADS (Breast Imaging-Reporting and Data System) levels and 4 types of breast density. The system can also localize 3 types of common abnormalities on mammography.&nbsp;&nbsp;</p><p>VinDr-Mammo has been trained and validated on about 50,000 studies collected from several hospitals in Vietnam. The bounding box annotation and disease labeling for this private dataset have been performed by top Vietnamese radiologists. The accuracy for BI-RADS classification is above 80%.</p>',
  'MAMMOGRAPHY.input':
    '<ul><li>An input to VinDr-Mammo must be a DICOM study that includes at least <strong>one of</strong> the following four views: Left MLO (Mediolateral Oblique), Left CC (Craniocaudal), Right MLO, Right CC</li><li>List of required DICOM tags for the input to VinDr-ChestXR. Required values for each tag are also given:<ul><li>Modality(0008, 0060): MG</li><li>BodyPartExamined(0018, 0015): BREAST</li><li>Laterality(0020,0060): At least one of the two tags must be equal to either “L” or “R”</li><li>ImageLaterality(0020,0062): At least one of the two tags must be equal to either “L” or “R”</li><li>ViewPosition(0018 0051): “CC” or “MLO”</li><li>PhotometricInterpretation(0028, 0004): Non-empty</li><li>PresentationIntentType(0008, 00068): FOR PRESENTATION</li><li>RescaleIntercept(0028, 1052): Non-empty</li><li>RescaleSlope(0028,1053): Non-empty</li><li>WindowCenter(0028,1050): Non-empty</li><li>WindowWidth(0028,1051): Non-empty</li><li>PixelPaddingValue(0028,0120): Non-empty</li></ul></li></ul>',
  'MAMMOGRAPHY.output':
    '<p>The analysis of VinDr-Mammo includes:</p><ul><li><p>A lesion detection: each lesion on the image is surrounded with a rectangle and labeled with one of the pre-defined lesion classes as indicated in below given list:</p><ul><li><p>Calcification</p></li><li><p>Lymph Node</p></li><li><p>Mass</p></li></ul></li><li><p>An image classification:</p><ul><li><p>The output of VinDr-Mammo also includes a BI-RADS (Breast Imaging-Reporting and Data System) classification and a density classification for each breast side</p></li><li><p>The classes BI-RADS 1, BI-RADS 2/3, and BI-RADS 4/5 correspond to the normal, benign, and suspicious statuses of the breast</p></li><li><p>The DENSITY class includes in terms Density A/Density B/Density C/Density D</p></li></ul></li></ul>',
  'LUNG_CT.content':
    '<p><strong>VinDr-ChestCT</strong>&nbsp;is a CAD tool&nbsp;for Chest CT interpretation. It is able to localize 04 types of common abnormalities on Chest CT scans.</p><p>The system will be trained and validated on about 30,000 studies collected from both public sources and several hospitals in Vietnam. The bounding box annotation and disease labeling for our private dataset have been performed by top Vietnamese radiologists.</p>',
  'LUNG_CT.input':
    '<ul><li><p>An input to VinDr-ChestCT must be a CT scan (series) of the chest in DICOM format at axial view</p></li><li><p>The series must have a minimum of 10 images</p></li><li><p>Patient age must be at least 16 years old</p></li><li><p>List of required DICOM tags for the input to VinDr-ChestXR. Required values for each tag are also given:</p><ul><li><p>Modality(0008, 0060): CT</p></li><li><p>BodyPartExamined(0018, 0015): “CHEST” or “THORAX”</p></li><li><p>RescaleIntercept(0028, 1052): Non-empty</p></li><li><p>RescaleSlope(0028,1053): Non-empty</p></li><li><p>WindowCenter(0028,1050): Non-empty</p></li><li><p>WindowWidth(0028,1051): Non-empty</p></li><li><p>ImagePositionPatient(0020, 0032): Non-empty</p></li></ul></li></ul>',
  'LUNG_CT.output':
    '<p>The analysis of VinDr-ChestCT includes:</p><ul><li><p>A lesion detection: each lesion on the image is surrounded with a rectangle and labeled with one of the pre-defined lesion classes as indicated in below given list:</p><ul><li><p>Consolidation</p></li><li><p>Mediastinal lymph nodes</p></li><li><p>Nodule/Mass</p></li><li><p>Pleural effusion</p></li></ul></li><li><p>An image classification: each series is classified in terms of normal/abnormal</p></li></ul>',
  'LIVER_CT.content':
    '<p><strong>VinDr-LiverCT</strong>&nbsp;is a CAD tool for abdomen CT interpretation. It is able to localize 04 types of common liver abnormalities on abdomen CT scans.&nbsp;&nbsp;</p><p>The system will be trained and validated on about 10,000 studies collected from both public sources and several hospitals in Vietnam. The bounding box annotation and disease labeling for our private dataset have been performed by top Vietnamese radiologists.</p>',
  'LIVER_CT.input':
    '<ul><li><p>An input to VinDr-LiverCT must be a CT scan (series) of the abdomen in DICOM format at axial view</p></li><li><p>The series must have a minimum of 10 images</p></li><li><p>Patient age must be at least 16 years old</p></li><li><p>The analysis of VinDr-LiverCT primarily applies to contrast-enhanced series at the venous phase. If a contrast-enhanced series is not available, VinDr-LiverCT can diagnose artery series instead</p></li><li><p>List of required DICOM tags for the input to VinDr-ChestXR. Required values for each tag are also given:</p><ul><li><p>Modality(0008, 0060): CT</p></li><li><p>BodyPartExamined(0018, 0015): “ABDOMEN”</p></li><li><p>RescaleIntercept(0028, 1052): Non-empty</p></li><li><p>RescaleSlope(0028,1053): Non-empty</p></li><li><p>WindowCenter(0028,1050): Non-empty</p></li><li><p>WindowWidth(0028,1051): Non-empty</p></li><li><p>SliceThickness(0018,0050): Non-empty</p></li></ul></li></ul>',
  'LIVER_CT.output':
    '<p>The analysis of VinDr-LiverCT includes:</p><ul><li><p>A lesion detection: each lesion on the image is surrounded with a rectangle and labeled with one of the pre-defined lesion classes as indicated in below given list:</p><ul><li><p>Biliary dilatation</p></li><li><p>Calcification</p></li><li><p>Cystic component</p></li><li><p>Mass</p></li></ul></li><li><p>An image classification: each series is classified in terms of normal/abnormal/fatty liver/ liver cirhosis</p></li></ul>',
  'BRAIN_CT.content':
    '<p><strong>VinDr-BrainCT</strong>&nbsp;is a CAD tool for brain CT interpretation. It is capable of segmenting hemorrhage lesions on brain CT scans.</p><p>The system will be trained and validated on about 30,000 studies collected from both public sources and several hospitals in Vietnam. The segmentation (on 3-D volumes) and disease labeling for our private dataset have been performed by top Vietnamese radiologists.</p>',
  'BRAIN_CT.input':
    '<ul><li><p>An input to VinDr-BrainCT must be a CT scan (series) of the brain in DICOM format at axial view</p></li><li><p>The series must have a minimum of 10 images</p></li><li><p>Patient age must be at least 16 years old</p></li><li><p>List of required DICOM tags for the input to VinDr-BrainCT. Required values for each tag are also given:</p><ul><li><p>Modality(0008, 0060): CT</p></li><li><p>BodyPartExamined(0018, 0015): “BRAIN” or “HEAD”</p></li><li><p>Contrast/BolusAgent(0018, 0010): Not Exist</p></li><li><p>Convolutionkernel(0018,1210): H31s”, “Hr40f”, “BrainA”, “STANDARD”, “SA” or “SB”</p></li><li><p>SliceThickness(0018,0050): “5.0”, “3.0” or “1.0”</p></li><li><p>RescaleIntercept(0028, 1052): Non-empty</p></li><li><p>RescaleSlope(0028,1053): Non-empty</p></li><li><p>WindowCenter(0028,1050): Non-empty</p></li><li><p>WindowWidth(0028,1051): Non-empty</p></li></ul></li></ul>',
  'BRAIN_CT.output':
    '<p>The analysis of VinDr-BrainCT includes:</p><ul><li><p>A lesion detection: each hemorrhage lesion on the image is surrounded by a segmentation</p></li><li><p>An image classification: each series is classified in terms of normal/abnormal</p></li></ul>',
  'BRAIN_MRI.content':
    '<p data-renderer-start-pos="13185"><strong data-renderer-mark="true">VinDr-BrainMR</strong>&nbsp;is a CAD tool&nbsp;for brain MRI interpretation. It is able to localize 14 types of common abnormalities on brain MRI scans.&nbsp;</p><p data-renderer-start-pos="13321">The system will be trained and validated on about 3,000 studies collected from both public sources and several hospitals in Vietnam. The bounding box annotation (on 3-D volumes) and disease labeling for our private dataset have been performed by top Vietnamese radiologists.&nbsp;</p>',
  'BRAIN_MRI.input':
    '<ul><li><p>An input to VinDr-BrainMR must be a MR scan (series) of the brain in DICOM format at the FLAIR sequence and axial view</p></li><li><p>The series must have a minimum of 10 images</p></li><li><p>Patient age must be at least 16 years old</p></li><li><p>List of required DICOM tags for the input to VinDr-ChestXR. Required values for each tag are also given:</p><ul><li><p>Modality(0008, 0060): MR</p></li><li><p>BodyPartExamined(0018, 0015): “BRAIN” or “HEAD”</p></li><li><p>RescaleIntercept(0028, 1052): Non-empty</p></li><li><p>RescaleSlope(0028,1053): Non-empty</p></li><li><p>WindowCenter(0028,1050): Non-empty</p></li><li><p>WindowWidth(0028,1051): Non-empty</p></li><li><p>ImagePositionPatient(0020, 0032): Non-empty</p></li></ul></li></ul>',
  'BRAIN_MRI.output':
    '<p>The analysis of VinDr-BrainMR includes:</p><ul><li><p>A lesion detection: each lesion on the image is surrounded with a rectangle and labeled with one of the pre-defined lesion classes as indicated in below given list:</p><ul><li><p>Arteriovenous malformation</p></li><li><p>Cavernoma</p></li><li><p>Cerebral atrophy</p></li><li><p>Cerebral edema</p></li><li><p>CSF-like lesion</p></li><li><p>Cyst component</p></li><li><p>Demyelination</p></li><li><p>Gliosis</p></li><li><p>Infiltration</p></li><li><p>Mass effect</p></li><li><p>Mass/Nodule</p></li><li><p>Midline shift</p></li><li><p>Sinus lesion</p></li><li><p>Ventricular dilation</p></li></ul></li><li><p>An image classification: each series is classified in terms of normal/abnormal</p></li></ul>',
};
